In [ ]:
"""
Ayon
1 2 3 4

"""
str1 = input(); print(str1)
lst = list(map(int,input().split(' ')))
a, b = map(int, input().split())
print(lst)

In [ ]:
"""
3 3
1 2 3
4 5 6
7 8 9
"""
n, m = map(int, input().split())
matrix = [list(map(int, input().split())) for i in range(n)]
print(matrix)

In [2]:
"""
Ayon YNOA
"""
str1, str2 = input().split()
sorted(str1.upper()) == sorted(str2.upper())

False

In [ ]:
max_min = float('-inf')

In [16]:
from collections import defaultdict

# Example 1: Default value is an integer (default 0)
count = defaultdict(int)
count[1] += 3
count['a'] += 1
count['b'] += 2
del count['b']
print(count)  # Output: defaultdict(<class 'int'>, {'a': 1, 'b': 2})

# Example 2: Default value is a list
groups = defaultdict(list)
groups['fruit'].append('apple')
groups['fruit'].append('banana')
groups['vegetable'].append('carrot')
print(groups)  # Output: defaultdict(<class 'list'>, {'fruit': ['apple', 'banana'], 'vegetable': ['carrot']})


defaultdict(<class 'int'>, {1: 3, 'a': 1, 'b': 2})
defaultdict(<class 'list'>, {'fruit': ['apple', 'banana'], 'vegetable': ['carrot']})


In [ ]:
import heapq
heap = []

heapq.heapify([3, 2, 1, 4, 5, 6]) # O(n)
# or
heapq.heappush(heap, 3456) # O(log n)
heapq.heappush(heap, 10)
heapq.heappush(heap, 211)

smallest = heap[0] # return the smallest element O(1)
smallest = heapq.heappop(heap) # get the smallest element O(log n)
heapq.heappushpop(heap, 100) # push and pop the smallest element

In [ ]:
from collections import deque

# Initialize a deque
dq = deque([1, 2, 3])

# Append elements to both ends
dq.append(4)         # Add to the right
dq.appendleft(0)     # Add to the left

# Remove elements from both ends
dq.pop()             # Remove from the right
dq.popleft()         # Remove from the left

# Rotate deque (positive = right, negative = left)
dq.rotate(1)         # Rotate right
dq.rotate(-2)        # Rotate left

print(dq)            # Output the deque


In [ ]:
import heapq

# Create a min-heap
min_heap = []

# Add elements to the heap
heapq.heappush(min_heap, 10)
heapq.heappush(min_heap, 5)
heapq.heappush(min_heap, 20)
heapq.heappush(min_heap, 1)

# Remove the smallest element
heapq.heappop(min_heap)

# Current state of the heap
print("Heap after pop:", min_heap)


In [ ]:
# subsequence: arr = [1, 2, 3, 4, 5, 6, 7, 8, 9] subsequences = [2, 4, 6, 8] or [1, 3] definition: A subsequence is a sequence that can be derived from another sequence by deleting some or no elements without changing the order of the remaining elements. For example, [2, 4, 6, 8] is a subsequence of [1, 2, 3, 4, 5, 6, 7, 8, 9] because it can be derived by deleting 1, 3, 5, 7, 9. However, [1, 3] is not a subsequence of [1, 2, 3, 4, 5, 6, 7, 8, 9] because the order of the elements is not preserved.
# subarray: arr = [1, 2, 3, 4, 5, 6, 7, 8, 9] subarrays = [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6], [5, 6, 7], [6, 7, 8], [7, 8, 9] definition: A subarray is a contiguous sequence of elements within an array. For example, [1, 2, 3] is a subarray of [1, 2, 3, 4, 5, 6, 7, 8, 9] because it is a contiguous sequence of elements within the array.

### Easy Level

1. Basic Operations
    - Traverse, insert, delete in arrays.
    - Find the largest and smallest element in an array.
    - Find the second largest and second smallest element.

2. Searching
    - Linear Search.
    - Binary Search.

3. Reverse an Array
    - Reverse the array in-place.
    - Reverse a subarray.

4. Rotate an Array
    - Rotate the array by k steps (cyclic rotation).
    - Rotate the array left and right.

5. Sorting Basics
    - Sort an array using Bubble Sort, Selection Sort, or Insertion Sort.
    - Sort an array of 0s, 1s, and 2s (Dutch National Flag Problem).

6. Sum and Prefix Problems
    - Find the sum of all elements in the array. -> sum(lst)
    - Check if a given array is a prefix of another. -> lst1[:len(lst2)] == lst2
    - Running Sum of 1D Array. -> [1, 3, 6, 12] -> [1, 4, 10, 22] or accumulate(lst)

7. Special Pattern Questions
    - Print all leaders in an array. -> (greater than or equal to all the elements to its right) [16, 17, 4, 3, 5, 2] -> [17, 5, 2]
    - Find the frequency of elements in an array. hash map (dictionary)

### Medium Level

1. Subarray Problems
    - Find the maximum sum of a subarray (Kadane's Algorithm).
    - Print all subarrays of an array.
    - Find subarrays with a given sum (both positive and negative numbers).

2. Sliding Window Problems
    - Maximum of all subarrays of size k.
    - Longest subarray with at most K distinct elements.
    - Longest substring with no more than K characters (for arrays treated as strings).

3. Two-Pointer Problems
    - Pair with a given sum in a sorted array. -> Use two pointers at the array's ends, adjusting them inward based on whether their sum is less than, equal to, or greater than the target, until they meet.
    - Move all zeros to the end of the array. -> use quicksort partitioning logic similar problem sort colors
    - Remove duplicates from a sorted array. -> [1, 1, 2, 2, 3, 4, 4] -> [1, 2, 3, 4]

4. Matrix Problems
    - Rotate a matrix 90 degrees clockwise/anticlockwise.
    - Spiral traversal of a matrix.
    - Search an element in a sorted matrix (row and column sorted).

5. Rearrangement Problems
    - Rearrange the array such that even index elements are greater.
    - Rearrange the array to alternate positive and negative numbers.
    - Rearrange an array so that the element at index i becomes the value at index arr[i].

6. Finding Missing or Duplicate Elements
    - Find the missing number in an array of size n containing numbers 1 to n.
    - Find all duplicates in an array.
    - Find the first repeating and first non-repeating element.

### Advanced Level

1. Greedy/Optimization Problems
    - Minimum number of jumps to reach the end of an array.
    - Trapping Rain Water Problem.
    - Gas Station Problem (circular array).

2. Partitioning and Segmentation
    - Partition an array into disjoint intervals with the smallest maximum difference.
    - Maximize the minimum difference in an array.

3. Binary Search Variants
    - Find the peak element in an array.
    - Search in a rotated sorted array.
    - Find the smallest missing positive integer.

4. Bit Manipulation
    - Find the element that appears only once when every other element appears twice.
    - XOR of all subarrays.

5. Dynamic Programming on Arrays
    - Longest Increasing Subsequence.
    - Maximum Product Subarray.
    - House Robber Problem.

6. Special Techniques
    - Merge two sorted arrays without extra space.
    - Count inversions in an array.
    - Find the majority element (Boyer-Moore Voting Algorithm).

### Competitive Programming Topics

1. Range Queries
    - Prefix sum and difference arrays.
    - Range Minimum Query using Segment Tree.
    - Range Updates using Fenwick Tree.

2. K-th Smallest/Largest
    - Find the k-th smallest/largest element using a heap.
    - Median of two sorted arrays.

3. Hashing and Frequency Problems
    - Longest subarray with sum divisible by k.
    - Find all pairs with a given difference.
    - Subarrays with equal number of 0s and 1s.


2 4 7 4 4 3 3 3 

In [10]:
# Trapezium pattern
"""
n = 3
. . * . . 
. * * * . 
* * * * * 
. * * * . 
. . * . . 
"""
n = 3
for i in range(2*n - 1):
    for j in range(2*n - 1):
        if i < n:
            if j >= n - i - 1 and j <= n + i - 1:
                print('*', end=' ')
            else:
                print('.', end=' ')
        else:
            if j >= i - n + 1 and j <= 3*n - i - 3:
                print('*', end=' ')
            else:
                print('.', end=' ')
    print()


. . * . . 
. * * * . 
* * * * * 
. * * * . 
. . * . . 


In [ ]:
# initial values can be 
init = 0, max(lst), min(lst), lst[0], float('-inf'), float('inf')

In [ ]:
# 3. Reverse an Array: T(n) = O(n), S(n) = O(1)
"""
1. Reverse an Array (In-Place)
2. Reverse a Subarray (In-Place)
Use two pointers (left at start, right at end), swap their elements, and move them inward until they meet.
"""
# 4. Rotate an Array
lst = [1, 2, 3, 4, 5, 6, 7]
k = 3
def rotate_array(nums, k):
    n = len(nums)
    k = k % n  # Handle cases where k > n

    # Helper function to reverse a portion of the array
    def reverse(start, end):
        while start < end:
            nums[start], nums[end] = nums[end], nums[start]
            start += 1
            end -= 1

    reverse(0, n - 1) # Step 1: Reverse the entire array
    reverse(0, k - 1) # Step 2: Reverse the first k elements
    reverse(k, n - 1) # Step 3: Reverse the rest of the elements

    return nums


In [ ]:
# 5. Sorting Basics (75. Sort Colors)
from typing import List

class Solution:
    def sortColors(self, nums: List[int]) -> None:
        i, j, ptr = 0, len(nums) - 1, 0

        while ptr <= j:
            if nums[ptr] == 0:
                nums[i], nums[ptr] = nums[ptr], nums[i]
                i += 1
                ptr += 1
            elif nums[ptr] == 1:
                ptr += 1
            elif nums[ptr] == 2:
                nums[j], nums[ptr] = nums[ptr], nums[j]
                j -= 1

In [9]:
# Medium Level
# 1. Subarray Problems
# Find the maximum sum of a subarray (Kadane's Algorithm).
"""
-1 2 3 -2 5
8
"""
n = 5
# lst = [-1, 2, 3, -2, 5]
lst = [-1, 2, 3, -2, 5, 12, -999]
lst = [1, 9, -3, 11, -71, 2, -12, 1, 5]
lst = [-12, -34]
res = lst[0]
current_max_sum = lst[0]
for i, ele in enumerate(lst[1:]):
    current_max_sum = max(ele, current_max_sum + ele)
    res = max(res, current_max_sum)
print(res)

# (560. Subarray Sum Equals K) Find Subarrays with a Given Sum (Both Positive and Negative Numbers): https://youtu.be/xvNwoz-ufXA?si=cZ6gQM6N99YEiGGA
class Solution:
    def subarraySum(self, nums: List[int], k: int) -> int:
        res = 0
        cur_sum = 0
        prefix_sum = { 0 : 1 }
        
        for n in range(len(nums)):
            cur_sum += nums[n]
            diff = cur_sum - k
            
            res += prefix_sum.get(diff, 0)
            prefix_sum[cur_sum] = 1 + prefix_sum.get(cur_sum, 0)
        
        return res



-12
[[3, 3]]


In [ ]:
# 2. Sliding Window Problems
    
# get all teh k sized contiguous subarrays -> take the min element of each subarray and return the max of those min elements
"""
3
2 4 19 7 8 4 5 3 12 7
[2 4 19] -> 2
[4 19 7] -> 4
[19 7 8] -> 7
[7 8 4] -> 4
[8 4 5] -> 4
[4 5 3] -> 3
[5 3 12] -> 3
[3 12 7] -> 3
max of all min elements = 7
"""

k = int(input())
lst = list(map(int, input().split()))
n = len(lst)
# Brute force
min_elements = [min(lst[i:i+k]) for i in range(n-k+1)]
print(max(min_elements))

# Optimized Approach
from collections import deque

def max_of_segment_minimums(lst, k):
    n = len(lst)
    dq = deque()
    max_min = float('-inf')

    for i in range(n):
        
        if dq and dq[0] < i - k + 1:
            dq.popleft()
        
        while dq and lst[dq[-1]] >= lst[i]:
            dq.pop()

        dq.append(i)

        if i >= k - 1:
            min_in_window = lst[dq[0]]
            max_min = max(max_min, min_in_window)

    return max_min


# Maximum of all subarrays of size k. (239. Sliding Window Maximum)
class Solution:
    def maxSlidingWindow(self, nums: List[int], k: int) -> List[int]:
        n = len(nums)
        dq = deque()
        res = []
        
        for i in range(n):
            
            if dq and dq[0] < i - k + 1:
                dq.popleft()
            
            while dq and nums[dq[-1]] < nums[i]:
                dq.pop()
            
            dq.append(i)
            
            if i >= k - 1:
                res.append(dq[0])
        
        return res
        
# Longest subarray with at most K distinct elements. (2958. Length of Longest Subarray With at Most K Frequency)
class Solution:
    def maxSubarrayLength(self, nums: List[int], k: int) -> int:
        res = 0
        count = defaultdict(int)
        l = 0
        for r in range(len(nums)):
            
            count[nums[r]] += 1
            
            while count[nums[r]] > k:
                count[nums[l]] -= 1
                l += 1
            
            res = max(res, r - l + 1)
        
        return res

# Longest substring with no more than K characters (for arrays treated as strings).
class Solution:
    def longestSubstring(self, s: str, k: int) -> int:
        res = 0
        count = defaultdict(int)
        l = 0
        for r in range(len(s)):
            count[s[r]] += 1
            
            while len(count) > k:
                count[s[l]] -= 1
                if count[s[l]] == 0:
                    del count[s[l]]
                l += 1
                
            res = max(res, r - l + 1)
        
        return res

In [23]:
def rotate_matrix_clockwise(matrix):
    n = len(matrix)
    # Step 1: Transpose the matrix
    for i in range(n):
        for j in range(i, len(matrix[0])):
            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]
    # Step 2: Reverse each row
    for row in matrix:
        row.reverse()
    return matrix

# Example
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]
print(rotate_matrix_clockwise(matrix))




def spiralOrder(matrix):
    rs, cs = len(matrix), len(matrix[0])
    rMin, rMax = 0, len(matrix) - 1
    cMin, cMax = 0, len(matrix[0]) - 1

    res = []
    while rMin <= rMax and cMin <= cMax:

        for c in range(cMin, cMax + 1):
            res.append(matrix[rMin][c])
        rMin += 1

        for r in range(rMin, rMax + 1):
            res.append(matrix[r][cMax])
        cMax -= 1

        if not (rMin <= rMax and cMin <= cMax):
            break

        for c in range(cMax, cMin - 1, -1):
            res.append(matrix[rMax][c])
        rMax -= 1

        for r in range(rMax, rMin - 1, -1):
            res.append(matrix[r][cMin])
        cMin += 1

    return res

"""
5 5
1 2 3 4 5 
6 7 8 9 10 
11 12 13 14 15 
16 17 18 19 20 
21 22 23 24 25 
"""
spiralOrder([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])


[[7, 4, 1], [8, 5, 2], [9, 6, 3]]


[1,
 2,
 3,
 4,
 5,
 10,
 15,
 20,
 25,
 24,
 23,
 22,
 21,
 16,
 11,
 6,
 7,
 8,
 9,
 14,
 19,
 18,
 17,
 12,
 13]

In [ ]:
class Node:
    """
    A class to represent a node in the linked list.
    Each node contains data and a pointer to the next node.
    """
    def __init__(self, data):
        self.data = data
        self.next = None


class LinkedList:
    """
    A class to represent the linked list.
    It contains a head node and methods to manipulate the list.
    """
    def __init__(self):
        self.head = None

    def is_empty(self):
        """Check if the linked list is empty."""
        return self.head is None

    def append(self, data):
        """Add a node with the given data at the end of the list."""
        new_node = Node(data)
        if self.head is None:
            self.head = new_node
            return
        current = self.head
        while current.next:
            current = current.next
        current.next = new_node

    def prepend(self, data):
        """Add a node with the given data at the beginning of the list."""
        new_node = Node(data)
        new_node.next = self.head
        self.head = new_node

    def insert_after(self, prev_node_data, data):
        """Insert a node with the given data after a specific node."""
        current = self.head
        while current and current.data != prev_node_data:
            current = current.next
        if current is None:
            print(f"Node with data {prev_node_data} not found.")
            return
        new_node = Node(data)
        new_node.next = current.next
        current.next = new_node

    def delete(self, key):
        """Delete the first node with the specified key (data)."""
        current = self.head
        if current and current.data == key:
            self.head = current.next
            current = None
            return
        prev = None
        while current and current.data != key:
            prev = current
            current = current.next
        if current is None:
            print(f"Node with data {key} not found.")
            return
        prev.next = current.next
        current = None

    def search(self, key):
        """Search for a node with the specified key (data)."""
        current = self.head
        while current:
            if current.data == key:
                return True
            current = current.next
        return False

    def traverse(self):
        """Traverse the linked list and print each node's data."""
        current = self.head
        while current:
            print(current.data, end=" -> ")
            current = current.next
        print("None")

    def reverse(self):
        """Reverse the linked list in place."""
        prev = None
        current = self.head
        while current:
            next_node = current.next
            current.next = prev
            prev = current
            current = next_node
        self.head = prev

# Example usage
if __name__ == "__main__":
    ll = LinkedList()
    ll.append(1)
    ll.append(2)
    ll.append(3)
    print("Initial List:")
    ll.traverse()

    ll.prepend(0)
    print("After Prepending 0:")
    ll.traverse()

    ll.insert_after(2, 2.5)
    print("After Inserting 2.5 after 2:")
    ll.traverse()

    ll.delete(2)
    print("After Deleting 2:")
    ll.traverse()

    print("Is 3 in the list?", ll.search(3))

    print("Reversed List:")
    ll.reverse()
    ll.traverse()


[LinkedList](linked-list.md)

[Recursion](https://youtu.be/Sa5PmCFF_zI?si=RuuIu83NBmQe9jNU)

In [6]:
def Subsequence(s):
    if(len(s)==0):
        return [""]

    lst_1 = Subsequence(s[1:])
    lst_ans = []
    for st in lst_1:
        lst_ans.append(st)
        lst_ans.append(s[0]+st)
    return lst_ans
lst = Subsequence('abc')
print(lst)

def subsequence(s,s_done):
    if(s==''):
        print(f"'{s_done}'")
        return

    subsequence(s[1:],s_done)
    subsequence(s[1:],s_done+s[0])

subsequence('abc','')

# Get Keypad Combination

phoneKeys = ['.;','abc','def','ghi','jkl','mno','pqrs','tu','vwx','yz']
def getKPC(str):
    if(len(str)==0):
        return [""]

    lst_ans = []
    last_combinations_lst = getKPC(str[1:])
    for preStr in last_combinations_lst:
        for comb_char in phoneKeys[int(str[0])]:
            lst_ans.append(comb_char+preStr)
    return lst_ans

print(getKPC('619'))

def getKPC2(s,s_ans):
    if(s==''):
        print(f"'{s_ans}'")
        return
    for keyChar in phoneKeys[int(s[0])]:
        getKPC2(s[1:],s_ans+keyChar)
getKPC2('678','')



['', 'a', 'b', 'ab', 'c', 'ac', 'bc', 'abc']
''
'c'
'b'
'bc'
'a'
'ac'
'ab'
'abc'
['pay', 'qay', 'ray', 'say', 'pby', 'qby', 'rby', 'sby', 'pcy', 'qcy', 'rcy', 'scy', 'paz', 'qaz', 'raz', 'saz', 'pbz', 'qbz', 'rbz', 'sbz', 'pcz', 'qcz', 'rcz', 'scz']
'ptv'
'ptw'
'ptx'
'puv'
'puw'
'pux'
'qtv'
'qtw'
'qtx'
'quv'
'quw'
'qux'
'rtv'
'rtw'
'rtx'
'ruv'
'ruw'
'rux'
'stv'
'stw'
'stx'
'suv'
'suw'
'sux'


In [14]:
# Get Stairs Path
def allpaths(n):
    if(n==0):
        return [""]
    elif (n < 0):
        return []

    lst_ans = []
    for lcl_str in allpaths(n-1):
        lst_ans.append("1"+lcl_str)
    for lcl_str in allpaths(n-2):
        lst_ans.append("2"+lcl_str)
    for lcl_str in allpaths(n-3):
        lst_ans.append("3"+lcl_str)

    return lst_ans


allP = allpaths(3)
print(allP)

def allpaths(n):
    if not n:
        return ['']
    lst_ans = []
    for i in range(1,n):
        for path in allpaths(n - i):
            lst_ans.append(path + str(i))

    lst_ans.append(str(n))
    print(lst_ans)
    return lst_ans

print(allpaths(4))

['111', '12', '21', '3']
['1']
['11', '2']
['1']
['111', '21', '12', '3']
['1']
['11', '2']
['1']
['1111', '211', '121', '31', '112', '22', '13', '4']
['1111', '211', '121', '31', '112', '22', '13', '4']


In [ ]:
def getmasepath1(x1,y1,x2,y2):
    if(x1==x2 and y1==y2):
        return [""]

    path_lst = []

    if(x1<x2):
        for aftHmove in getmasepath1(x1 + 1,y1 , x2, y2):
            path_lst.append("v"+ aftHmove)
    if(y1<y2):
        for aftVmove in getmasepath1(x1,y1+1,x2,y2):
            path_lst.append("h"+aftVmove)

    return path_lst
mzPath = getmasepath1(1,1,3,3)
print(mzPath)

def getmasepath2(x1,y1,x2,y2,s_ans):
    if(x1==x2 and y1==y2):
        print(s_ans)
    if(x1>x2 or y1>y2):
        return

    getmasepath2(x1+1,y1,x2,y2,s_ans+'h')
    getmasepath2(x1,y1+1,x2,y2,s_ans+'v')

getmasepath2(1,1,3,3,'')

In [23]:
def permutations(s, s_dones):
    if(len(s)==0):
        print(s_dones,end = ' ')
        return
    for i in range(len(s)):
        permutations(s[:i]+s[i+1:],s_dones+s[i])

def permutations(s):
    if len(s) == 1:
        return [s]

    premutations_list = []
    for i in range(len(s)): 
        res = permutations(s[:i]+s[i+1:])
        for r in res:
            premutations_list.append(s[i]+r)
    
    return premutations_list
        
# permutations('abc','')
print("Permutations", permutations('abcd'))

Permutations ['abcd', 'abdc', 'acbd', 'acdb', 'adbc', 'adcb', 'bacd', 'badc', 'bcad', 'bcda', 'bdac', 'bdca', 'cabd', 'cadb', 'cbad', 'cbda', 'cdab', 'cdba', 'dabc', 'dacb', 'dbac', 'dbca', 'dcab', 'dcba']


In [25]:
"""
6 7
0 1 0 0 0 0 0
0 1 0 1 1 1 0
0 0 0 0 0 0 0
1 0 1 1 0 1 1
1 0 1 1 0 1 1
1 0 0 0 0 0 0
"""
def floodfill(maze,row,col,psf):
    if(row<0 or col<0 or row>=len(maze) or col>=len(maze[0]) or maze[row][col]==True):
        return

    if(row == len(maze)-1 and col == len(maze[0])-1):
        print(psf)
        return
    
    maze[row][col] = True
    floodfill(maze,row,col+1,psf+'r')
    floodfill(maze,row+1,col,psf+'b')
    floodfill(maze,row,col-1,psf+'l')
    floodfill(maze,row-1,col,psf+'t')
    maze[row][col] = False
    
map_2D = []
i,j = map(int,input().split())
for i in range(i):
    map_2D.append(list(map(int,input().split())))

print(map_2D)
floodfill(map_2D,0,0,'')

[[0, 1, 0, 0, 0, 0, 0], [0, 1, 0, 1, 1, 1, 0], [0, 0, 0, 0, 0, 0, 0], [1, 0, 1, 1, 0, 1, 1], [1, 0, 1, 1, 0, 1, 1], [1, 0, 0, 0, 0, 0, 0]]
bbrrrrbbbrr
bbrrttrrrrbbllbbbrr
bbrbbbrrrrr


In [26]:
def isItaSafePlaceForTheQueen(chess,row,col):
    for r in range(row-1,-1,-1):
        if(chess[r][col]):
            return False
    for r,c in zip(range(row-1,-1,-1),range(col-1,-1,-1)):
        if (chess[r][c]):
            return False
    for r,c in zip(range(row-1,-1,-1),range(col+1,len(chess[0]))):
        if(chess[r][c]):
            return False
    return True


def printNQueens(chess,row,qsf):
    if row==len(chess):
        print(qsf)
        return

    for col in range(len(chess[0])):
        if isItaSafePlaceForTheQueen(chess,row,col)==False:
            continue

        chess[row][col] = 1
        printNQueens(chess,row+1,f"{qsf} {row}-{col},")
        chess[row][col] = 0

import numpy as np
chess = np.zeros((4,4),dtype=int)

printNQueens(chess,0,"")

 0-1, 1-3, 2-0, 3-2,
 0-2, 1-0, 2-3, 3-1,


In [ ]:
# Implement Stack using Queues

from queue import Queue

class Stack:
    def __init__(self):
        self.queue1 = Queue()  # primary queue
        self.queue2 = Queue()  # secondary queue

    def push(self, x):
        # Push element to the primary queue
        self.queue1.put(x)

    def pop(self):
        if self.queue1.empty():
            return None  # If the stack is empty, return None
        
        # Move all elements except the last to the secondary queue
        while self.queue1.qsize() > 1:
            self.queue2.put(self.queue1.get())

        # Pop the last element (which is the top of the stack)
        top = self.queue1.get()

        # Swap the queues, so queue1 always holds the elements
        self.queue1, self.queue2 = self.queue2, self.queue1
        
        return top

    def top(self):
        if self.queue1.empty():
            return None  # If the stack is empty, return None
        
        # Move all elements except the last to the secondary queue
        while self.queue1.qsize() > 1:
            self.queue2.put(self.queue1.get())

        # Get the last element (which is the top of the stack)
        top = self.queue1.get()

        # Put the top element back into queue1
        self.queue2.put(top)

        # Swap the queues
        self.queue1, self.queue2 = self.queue2, self.queue1
        
        return top

    def empty(self):
        return self.queue1.empty()

# Example usage:
stack = Stack()
stack.push(1)
stack.push(2)
stack.push(3)
print(stack.pop())  # Output: 3
print(stack.top())  # Output: 2
print(stack.pop())  # Output: 2
print(stack.empty()) # Output: False


In [1]:
# Implement Stack using Arrays

class Stack:
    def __init__(self):
        self.stack = []  # Initializing an empty stack
    
    def is_empty(self):
        return len(self.stack) == 0
    
    def push(self, item):
        self.stack.append(item)  # Add item to the top of the stack
    
    def pop(self):
        if not self.is_empty():
            return self.stack.pop()  # Remove and return the top item
        else:
            return "Stack is empty"
    
    def peek(self):
        if not self.is_empty():
            return self.stack[-1]  # Return the top item without removing it
        else:
            return "Stack is empty"
    
    def size(self):
        return len(self.stack)  # Return the size of the stack

# Example usage
stack = Stack()
stack.push(10)
stack.push(20)
stack.push(30)

print(stack.pop())  # 30
print(stack.peek())  # 20
print(stack.size())  # 2


# Valid Parentheses
# Check if a given string containing parentheses is valid (balanced). 

def isValid(s: str) -> bool:
    stack = []
    # Define a mapping of closing brackets to their corresponding opening brackets
    mapping = {')': '(', '}': '{', ']': '['}
    
    # Iterate over each character in the string
    for char in s:
        if char in mapping:
            # Pop the top of the stack if it's a matching opening bracket
            top_element = stack.pop() if stack else '#'
            if top_element != mapping[char]:
                return False
        else:
            # Push opening brackets onto the stack
            stack.append(char)
    
    # The stack should be empty if all opening brackets have been matched
    return not stack

print(isValid("()"))         # True
print(isValid("()[]{}"))     # True
print(isValid("(]"))         # False
print(isValid("([)]"))       # False
print(isValid("{[]}"))       # True



30
20
2
True
True
False
False
True


In [3]:
def remove_characters(target, reference):
    reference = set(reference)
    res = ''.join(ch for ch in target if ch not in reference)
    return res

target = "Programming"
reference = "gra"
remove_characters(target, reference)

'Pommin'

In [ ]:
# Breadth-First Search (BFS) and Depth-First Search (DFS) 

class Node:
    def __init__(self, value):
        self.value = value
        self.children = []

    def add_child(self, child_node):
        self.children.append(child_node)


# Breadth-First Search (BFS)
def bfs(root):
    if not root:
        return []

    queue = [root]
    result = []

    while queue:
        current = queue.pop(0)
        result.append(current.value)

        # Add all children of the current node to the queue
        for child in current.children:
            queue.append(child)

    return result


# Depth-First Search (DFS)
def dfs(root):
    if not root:
        return []

    stack = [root]
    result = []

    while stack:
        current = stack.pop()
        result.append(current.value)

        # Add all children to the stack in reverse order (to maintain order during pop)
        for child in reversed(current.children):
            stack.append(child)

    return result


# Example Usage
if __name__ == "__main__":
    # Creating a tree
    root = Node(1)
    child1 = Node(2)
    child2 = Node(3)
    child3 = Node(4)
    child4 = Node(5)
    child5 = Node(6)

    root.add_child(child1)
    root.add_child(child2)
    child1.add_child(child3)
    child1.add_child(child4)
    child2.add_child(child5)

    # Perform BFS and DFS
    print("BFS:", bfs(root))  # Output: [1, 2, 3, 4, 5, 6]
    print("DFS:", dfs(root))  # Output: [1, 2, 4, 5, 3, 6]
